# Importing TensorFlow
To use TensorFlow, we need to import the library. We imported it and optionally gave it the name "tf", so the modules can be accessed by tf.module-name:

In [1]:
import tensorflow as tf

# Building a Graph
As we said before, TensorFlow works as a graph computational model. Let's create our first graph which we named as graph1.

In [2]:
graph1 = tf.Graph()

Now we call the TensorFlow functions that construct new tf.Operation and tf.Tensor objects and add them to the graph1. As mentioned, each tf.Operation is a node and each tf.Tensor is an edge in the graph.

Lets add 2 constants to our graph. For example, calling tf.constant([2], name = 'constant_a') adds a single tf.Operation to the default graph. This operation produces the value 2, and returns a tf.Tensor that represents the value of the constant.
Notice: tf.constant([2], name="constant_a") creates a new tf.Operation named "constant_a" and returns a tf.Tensor named "constant_a:0".

In [3]:
with graph1.as_default():
    a = tf.constant([2], name = 'constant_a')
    b = tf.constant([3], name = 'constant_b')

In [4]:
a

<tf.Tensor 'constant_a:0' shape=(1,) dtype=int32>

In [5]:
sess = tf.Session(graph = graph1)
result = sess.run(a)
print(result)
sess.close()

[2]


In [6]:
with graph1.as_default():
    c = tf.add(a, b)
    #c = a + b is also a way to define the sum of the terms

In [7]:
c

<tf.Tensor 'Add:0' shape=(1,) dtype=int32>

In [8]:
sess = tf.Session(graph = graph1)

In [9]:
result = sess.run(c)
print(result)

[5]


In [10]:
sess.close()

# Defining multidimensional arrays using TensorFlow

In [11]:
graph2 = tf.Graph()
with graph2.as_default():
    Scalar = tf.constant(2)
    Vector = tf.constant([5,6,2])
    Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )
with tf.Session(graph = graph2) as sess:
    result = sess.run(Scalar)
    print ("Scalar (1 entry):\n %s \n" % result)
    result = sess.run(Vector)
    print ("Vector (3 entries) :\n %s \n" % result)
    result = sess.run(Matrix)
    print ("Matrix (3x3 entries):\n %s \n" % result)
    result = sess.run(Tensor)
    print ("Tensor (3x3x3 entries) :\n %s \n" % result)

Scalar (1 entry):
 2 

Vector (3 entries) :
 [5 6 2] 

Matrix (3x3 entries):
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Tensor (3x3x3 entries) :
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 



In [12]:
Scalar.shape

TensorShape([])

In [13]:
Tensor.shape

TensorShape([Dimension(3), Dimension(3), Dimension(3)])

# Variables

In [15]:
v = tf.Variable(0)

In [16]:
update = tf.assign(v, v+1)

In [17]:
init_op = tf.global_variables_initializer()

In [18]:
with tf.Session() as session:
    session.run(init_op)
    print(session.run(v))
    for _ in range(3):
        session.run(update)
        print(session.run(v))

0
1
2
3


# Placeholders

Now we know how to manipulate variables inside TensorFlow graph, but what about feeding data outside of a TensorFlow graph?

If you want to feed data to a TensorFlow graph from outside a graph, you will need to use placeholders.

So what are these placeholders and what do they do?

Placeholders can be seen as "holes" in your model, "holes" which you will pass the data to, you can create them using 
tf.placeholder(datatype), where datatype specifies the type of data (integers, floating points, strings, booleans) along with its precision (8, 16, 32, 64) bits.



In [19]:
a = tf.placeholder(tf.float32)

In [20]:
b = a * 2

To pass the data into the model we call the session with an extra argument feed_dict in which we should pass a dictionary with each placeholder name followed by its respective data

In [21]:
with tf.Session() as sess:
    result = sess.run(b,feed_dict={a:3.5})
    print (result)

7.0


In [22]:
dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }

with tf.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print (result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]
